name: "Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  jsonResult:
    description: "txt file with the output of the tests"
    required: true
    default: "error: no test!"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "dist/index.js"
